// Generated by scripts/gen-linux-matrix.mjs from .kiro/specs/audio-video-polish/linux-capability-matrix.md
// Do not edit by hand.

export type LinuxCapabilityStatus = 'supported' | 'degraded' | 'unsupported';

export interface LinuxCapabilityRow {
  desktopEnv: string;
  compositor: 'wayland' | 'x11';
  videoCapture: 'supported' | 'unsupported';
  audioCapture: 'supported' | 'degraded' | 'unsupported';
  combinedStatus: LinuxCapabilityStatus;
  userMessage: string | null;
}

export const rows: LinuxCapabilityRow[] = [
  {
    desktopEnv: "gnome",
    compositor: "wayland",
    videoCapture: "supported",
    audioCapture: "degraded",
    combinedStatus: "degraded",
    userMessage: "Linux native share on GNOME/Wayland is degraded: remote mic and system-audio still share one subscriber volume slot on Linux.",
  },
  {
    desktopEnv: "kde",
    compositor: "wayland",
    videoCapture: "supported",
    audioCapture: "degraded",
    combinedStatus: "degraded",
    userMessage: "Linux native share on KDE/Wayland is degraded: remote mic and system-audio still share one subscriber volume slot on Linux.",
  },
  {
    desktopEnv: "sway",
    compositor: "wayland",
    videoCapture: "unsupported",
    audioCapture: "unsupported",
    combinedStatus: "unsupported",
    userMessage: "Linux native share is not supported on Sway/Wayland in the checked-in Wavis matrix yet; use GNOME, KDE, or an X11 session instead.",
  },
  {
    desktopEnv: "gnome",
    compositor: "x11",
    videoCapture: "supported",
    audioCapture: "degraded",
    combinedStatus: "degraded",
    userMessage: "Linux native share on GNOME/X11 is degraded: remote mic and system-audio still share one subscriber volume slot on Linux.",
  },
  {
    desktopEnv: "kde",
    compositor: "x11",
    videoCapture: "supported",
    audioCapture: "degraded",
    combinedStatus: "degraded",
    userMessage: "Linux native share on KDE/X11 is degraded: remote mic and system-audio still share one subscriber volume slot on Linux.",
  },
  {
    desktopEnv: "xfce",
    compositor: "x11",
    videoCapture: "supported",
    audioCapture: "degraded",
    combinedStatus: "degraded",
    userMessage: "Linux native share on XFCE/X11 is degraded: remote mic and system-audio still share one subscriber volume slot on Linux.",
  },
];

const UNKNOWN_COMBINATION_MESSAGE =
  'Linux native share on this desktop is not in the checked-in Wavis capability matrix yet; share will proceed with degraded expectations.';

export function lookupLinuxCapability(
  desktopEnv: string,
  compositor: 'wayland' | 'x11',
): LinuxCapabilityRow {
  const normalizedDesktopEnv = desktopEnv.trim().toLowerCase();
  return (
    rows.find((row) => row.desktopEnv === normalizedDesktopEnv && row.compositor === compositor) ?? {
      desktopEnv: normalizedDesktopEnv || 'unknown',
      compositor,
      videoCapture: 'unsupported',
      audioCapture: 'unsupported',
      combinedStatus: 'degraded',
      userMessage: UNKNOWN_COMBINATION_MESSAGE,
    }
  );
}
