#!/usr/bin/env python3
"""Generate tools/compat/machines.local.toml from Terraform outputs.

Reads the live public IPs and SSH credentials from `terraform output -json`
in the dev environment and writes a ready-to-use machines.local.toml.

Usage:
    # From repo root — default Terraform dir
    python tools/compat/gen-machines-local.py

    # Explicit Terraform directory
    python tools/compat/gen-machines-local.py --tf-dir infrastructure/environments/dev

    # Preview without writing (dry run)
    python tools/compat/gen-machines-local.py --dry-run

    # Custom output path
    python tools/compat/gen-machines-local.py --out path/to/machines.local.toml

Prerequisites:
    - Terraform installed and authenticated (same credentials used for `terraform apply`)
    - enable_mac_compat=true applied in the target workspace
    - Run `terraform init` in the Terraform directory at least once
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path
from textwrap import dedent

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_TF_DIR = REPO_ROOT / "infrastructure" / "environments" / "dev"
DEFAULT_OUT = REPO_ROOT / "tools" / "compat" / "machines.local.toml"


def run_terraform_output(tf_dir: Path) -> dict:
    """Run `terraform output -json` and return parsed JSON."""
    result = subprocess.run(
        ["terraform", "output", "-json"],
        cwd=tf_dir,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print(f"ERROR: terraform output failed in {tf_dir}", file=sys.stderr)
        print(result.stderr, file=sys.stderr)
        sys.exit(1)
    try:
        return json.loads(result.stdout)
    except json.JSONDecodeError as exc:
        print(f"ERROR: could not parse terraform output JSON: {exc}", file=sys.stderr)
        sys.exit(1)


def extract(outputs: dict, key: str) -> str | None:
    """Return the value of a Terraform output, or None if absent/null."""
    entry = outputs.get(key, {})
    value = entry.get("value")
    return value if value is not None else None


def build_toml(outputs: dict) -> str:
    """Build machines.local.toml content from Terraform outputs."""
    intel_enabled = extract(outputs, "mac_compat_intel_enabled")
    arm_enabled = extract(outputs, "mac_compat_arm_enabled")

    if not intel_enabled and not arm_enabled:
        print(
            "WARNING: no Mac compat hosts are enabled in Terraform outputs.\n"
            "         Enable at least one:\n"
            "           terraform apply -var='enable_mac_compat_intel=true'\n"
            "           terraform apply -var='enable_mac_compat_arm=true'\n"
            "         Then re-run this script.",
            file=sys.stderr,
        )

    intel_ip = extract(outputs, "mac_compat_intel_public_ip")
    arm_ip = extract(outputs, "mac_compat_arm_public_ip")
    ssh_key = extract(outputs, "mac_compat_ssh_key_file") or "infrastructure/wavis-backend-dev-jey.pem"
    ssh_user = extract(outputs, "mac_compat_ssh_user") or "ec2-user"
    intel_ami = extract(outputs, "mac_compat_intel_ami") or "unknown"
    arm_ami = extract(outputs, "mac_compat_arm_ami") or "unknown"
    target_macos = extract(outputs, "mac_intel_target_macos") or "ventura"

    def host_or_placeholder(ip: str | None, label: str) -> str:
        return ip if ip else f"<{label}-ip-not-available>"

    lines = [
        "# tools/compat/machines.local.toml — generated by gen-machines-local.py",
        "# DO NOT COMMIT — this file is gitignored.",
        "# Regenerate after terraform apply:",
        "#   python tools/compat/gen-machines-local.py",
        "#",
        "# Source Terraform dir: infrastructure/environments/dev",
    ]

    if intel_enabled:
        lines.append(f"# Intel host: macOS {target_macos}  AMI: {intel_ami}")
    if arm_enabled:
        lines.append(f"# ARM host:   macOS 26.x           AMI: {arm_ami}")

    if intel_enabled:
        if not intel_ip:
            print(
                "WARNING: mac_compat_intel_public_ip is null — instance may still be starting.",
                file=sys.stderr,
            )

        if target_macos == "ventura":
            name = "mac-ventura-intel"
            macos = "13.x"
            notes = "AWS EC2 mac1.metal — macOS 13 Ventura, Intel"
            tiers = '["t0", "t1", "t2", "t3"]'
            extra = []
        else:
            name = "mac-bigsur-intel"
            macos = "11.x"
            notes = "AWS EC2 mac1.metal — macOS 11 Big Sur, Intel (no SCK)"
            tiers = '["t0", "t1", "t2"]  # t3 skipped: SCK absent on Big Sur'
            extra = ['expected_failures = ["audio_enum"]  # no audio process tap on 11.x']

        lines += [
            "",
            "[[machines]]",
            f'name    = "{name}"',
            f'host    = "{host_or_placeholder(intel_ip, "intel")}"',
            f'user    = "{ssh_user}"',
            f'ssh_key = "{ssh_key}"',
            'arch    = "x86_64"',
            f'macos   = "{macos}"',
            f'notes   = "{notes}"',
            f'tiers   = {tiers}',
        ] + extra

    if arm_enabled:
        if not arm_ip:
            print(
                "WARNING: mac_compat_arm_public_ip is null — instance may still be starting.",
                file=sys.stderr,
            )

        lines += [
            "",
            "[[machines]]",
            'name    = "mac-arm"',
            f'host    = "{host_or_placeholder(arm_ip, "arm")}"',
            f'user    = "{ssh_user}"',
            f'ssh_key = "{ssh_key}"',
            'arch    = "arm64"',
            'macos   = "26.x"',
            'notes   = "AWS EC2 mac2.metal — macOS 26 Tahoe, ARM64 baseline reference"',
            'tiers   = ["t0", "t1", "t2", "t3"]',
        ]

    return "\n".join(lines) + "\n"


def verify_ssh(machines: list[dict]) -> None:
    """Quick SSH connectivity check for each machine (informational only)."""
    print("\nSSH connectivity check:")
    for m in machines:
        host = m["host"]
        user = m["user"]
        key = m["ssh_key"]
        if host.startswith("<"):
            print(f"  SKIP  {m['name']} — IP not available")
            continue
        result = subprocess.run(
            [
                "ssh",
                "-i", key,
                "-o", "ConnectTimeout=8",
                "-o", "StrictHostKeyChecking=no",
                "-o", "BatchMode=yes",
                f"{user}@{host}",
                "sw_vers -productVersion",
            ],
            capture_output=True,
            text=True,
        )
        if result.returncode == 0:
            version = result.stdout.strip()
            print(f"  OK    {m['name']}  ({host})  macOS {version}")
        else:
            err = result.stderr.strip().splitlines()[0] if result.stderr.strip() else "no output"
            print(f"  FAIL  {m['name']}  ({host})  — {err}")


def parse_toml_machines(toml_text: str) -> list[dict]:
    """Minimal TOML parser to extract [[machines]] entries for SSH check."""
    try:
        try:
            import tomllib
        except ModuleNotFoundError:
            import tomli as tomllib  # type: ignore[no-redef]
        data = tomllib.loads(toml_text)
        return data.get("machines", [])
    except Exception:
        return []


def print_instance_commands(outputs: dict, region: str = "us-east-2") -> None:
    """Print the stop/start/teardown commands for the allocated Mac instances."""
    ids = []
    for key in ("mac_compat_intel_instance_id", "mac_compat_arm_instance_id"):
        v = extract(outputs, key)
        if v:
            ids.append(v)

    if not ids:
        print(
            "\n(Instance IDs not available — run terraform apply first to see stop/start commands.)"
        )
        return

    ids_str = " ".join(ids)
    print(dedent(f"""
        ── Cost-saving commands (24-hour billing window) ──────────────────────────────

        Dedicated Hosts are charged from allocation to release. If you plan to run
        tests again within 24 hours, STOP instances instead of destroying them.
        The hosts keep billing either way, but you avoid paying a second 24-hour
        minimum on a fresh allocation.

        Stop instances between runs (hosts stay allocated, no re-provisioning cost):
          aws ec2 stop-instances --region {region} --instance-ids {ids_str}

        Start instances before the next run (IPs may change — re-run this script after):
          aws ec2 start-instances --region {region} --instance-ids {ids_str}
          python tools/compat/gen-machines-local.py --check-ssh

        Full teardown when done for the day (releases hosts, stops all billing):
          aws ec2 terminate-instances --region {region} --instance-ids {ids_str}
          terraform -chdir=infrastructure/environments/dev destroy \\
            -target=aws_ec2_host.compat_intel \\
            -target=aws_ec2_host.compat_arm \\
            -var="enable_mac_compat_intel=true" \\
            -var="enable_mac_compat_arm=true"
          # Verify in AWS Console: EC2 → Dedicated Hosts → all hosts show "Released"
    """))


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate tools/compat/machines.local.toml from Terraform outputs."
    )
    parser.add_argument(
        "--tf-dir",
        type=Path,
        default=DEFAULT_TF_DIR,
        help="Terraform working directory (default: infrastructure/environments/dev)",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=DEFAULT_OUT,
        help="Output path for machines.local.toml (default: tools/compat/machines.local.toml)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the generated TOML to stdout without writing the file",
    )
    parser.add_argument(
        "--check-ssh",
        action="store_true",
        help="After writing, attempt SSH to each machine and report connectivity",
    )
    args = parser.parse_args()

    tf_dir = args.tf_dir.resolve() if not args.tf_dir.is_absolute() else args.tf_dir
    if not tf_dir.is_dir():
        print(f"ERROR: Terraform directory not found: {tf_dir}", file=sys.stderr)
        sys.exit(1)

    print(f"Reading Terraform outputs from: {tf_dir}")
    outputs = run_terraform_output(tf_dir)
    toml_content = build_toml(outputs)

    if args.dry_run:
        print("\n--- machines.local.toml (dry run) ---")
        print(toml_content)
        print("--- end ---")
        print_instance_commands(outputs)
        return

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(toml_content, encoding="utf-8")
    print(f"Written: {args.out}")

    if args.check_ssh:
        machines = parse_toml_machines(toml_content)
        if machines:
            verify_ssh(machines)
        else:
            print("WARNING: could not parse machines from generated TOML for SSH check.")

    print_instance_commands(outputs)


if __name__ == "__main__":
    main()
