//! SFU bridge trait definitions for room lifecycle and media signaling.
//!
//! **Owns:** the abstract interface (`SfuRoomManager`, `SfuSignalingProxy`)
//! that all SFU implementations must satisfy, plus shared types
//! (`SfuRoomHandle`, `SfuError`, `SfuHealth`).
//!
//! **Implementations:**
//! - `domain::livekit_bridge::LiveKitSfuBridge` — real LiveKit backend,
//!   always compiled (the `livekit-api` crate is a hard dependency).
//!   Implements `SfuRoomManager` only — LiveKit clients negotiate WebRTC
//!   directly with the LiveKit server.
//! - `domain::mock_sfu_bridge::MockSfuBridge` — test-only mock, gated
//!   behind `#[cfg(any(test, feature = "test-support"))]`. Records calls
//!   for assertion and returns configurable results. Never reachable in
//!   production builds.
//!
//! **Feature flags:**
//! - `test-support` — exposes `mock_sfu_bridge` to integration tests
//!   (`tests/` directory). Unit tests get it automatically via `#[cfg(test)]`.
//!   Production builds (`cargo build --release`) never include mock logic.
//!
//! **Does not own:** token signing (that is `domain::jwt`), SDP/ICE relay
//! logic (that is `domain::sfu_sdp`), or room lifecycle orchestration
//! (that is `domain::sfu_relay`).

use async_trait::async_trait;
use shared::signaling::IceCandidate;

/// Opaque handle to an SFU-side room. Returned by `create_room()`.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct SfuRoomHandle(pub String);

/// Health status of the SFU.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SfuHealth {
    Available,
    Unavailable(String),
    /// EC2 instance is booting; LiveKit is not yet reachable.
    Starting {
        since: std::time::Instant,
    },
}

/// Errors from SFU operations.
#[derive(Debug, thiserror::Error)]
pub enum SfuError {
    #[error("SFU unavailable: {0}")]
    Unavailable(String),
    #[error("room not found: {0}")]
    RoomNotFound(String),
    #[error("participant error: {0}")]
    ParticipantError(String),
    #[error("transport error: {0}")]
    TransportError(String),
    #[error("token error: {0}")]
    TokenError(String),
    #[error("room is full")]
    RoomFull,
    #[error("invite exhausted")]
    InviteExhausted,
    #[error("invalid input: {0}")]
    InvalidInput(String),
    #[error("unauthorized: {0}")]
    Unauthorized(String),
}

/// Room lifecycle management trait. All SFU implementations must implement this.
///
/// Token issuance is NOT part of this trait. The backend owns JWT signing via
/// `domain/jwt.rs`. The SFU only validates tokens using the shared secret.
#[async_trait]
pub trait SfuRoomManager: Send + Sync {
    async fn create_room(&self, room_id: &str) -> Result<SfuRoomHandle, SfuError>;
    async fn destroy_room(&self, handle: &SfuRoomHandle) -> Result<(), SfuError>;

    /// Register a participant with the SFU. Does NOT issue a token —
    /// the backend signs the MediaToken JWT after this call succeeds.
    async fn add_participant(
        &self,
        handle: &SfuRoomHandle,
        participant_id: &str,
    ) -> Result<(), SfuError>;

    async fn remove_participant(
        &self,
        handle: &SfuRoomHandle,
        participant_id: &str,
    ) -> Result<(), SfuError>;

    async fn health_check(&self) -> Result<SfuHealth, SfuError>;
}

/// SDP/ICE forwarding trait for SFUs that need the backend to proxy WebRTC
/// negotiation. LiveKit does NOT implement this — its clients handle WebRTC
/// negotiation directly with the LiveKit server.
#[async_trait]
pub trait SfuSignalingProxy: Send + Sync {
    async fn forward_offer(
        &self,
        handle: &SfuRoomHandle,
        participant_id: &str,
        sdp: &str,
    ) -> Result<String, SfuError>;

    async fn forward_ice_candidate(
        &self,
        handle: &SfuRoomHandle,
        participant_id: &str,
        candidate: &IceCandidate,
    ) -> Result<(), SfuError>;

    /// Receive ICE candidates generated by the SFU for a given participant.
    /// The backend polls these and forwards them to the client over the signaling WebSocket.
    async fn poll_sfu_ice_candidates(
        &self,
        handle: &SfuRoomHandle,
        participant_id: &str,
    ) -> Result<Vec<IceCandidate>, SfuError>;
}
